version: '3.8'
services:
    postgres:
        image: postgres
        env_file:
            - postgres.env
        ports:
            - 5432:5432
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 80:8084
        env_file:
            - postgres.env
